services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap-ber
    ports:
      - "389:389"      # Standard LDAP port
      - "636:636"      # LDAP over SSL
    # volumes:
    #   - ./ldap_bootstrap:/container/service/slapd/assets/config/bootstrap/ldif/
    environment:
      - LDAP_ORGANISATION=TestOrg
      - LDAP_DOMAIN=testorg.com
      - LDAP_ADMIN_PASSWORD=admin123
    networks:
      - ber_net

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin-ber
    ports:
      - "8080:80"      # Web interface port
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - ber_net

networks:
  ber_net:
    driver: bridge 